# Generated by Django 5.1.6 on 2025-05-23 19:24

import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0009_courses_hours_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingcourses',
            name='age',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('5-7', '5-7'), ('7-9', '7-9'), ('9-11', '9-11'), ('11-13', '11-13'), ('13+', '13+')], default='5-7', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='parentContact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
